In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
df=pd.read_parquet("../data/data_hemnet.parquet")
df.shape

(717, 46)

In [4]:
df.head(3)

,id,coordinate,address,location_name,typeSummary,iconName,project,new_construction,ongoing_bidding,foreclosure,upcoming,price,price_per_area,has_price_change,rooms,fee,age_string,age,deactivated_before_open_house,land_area,small_image_url,medium_image_url,url,labels,state_labels,visible_project_units,show_visible_project_units,user_saved,save_button_label,broker_logo_url,broker_agency_name,locations_string,should_display_showings,should_highlight_showings,living_space.table,trackingData.listingId,trackingData.listingType,trackingData.listingPackageType,trackingData.listingState,trackingData.listingStatus,price_change,area,date,broker_name,broker_phone,broker_email
0,19325173,"[59.3239555, 18.0685062]",Lilla Nygatan 11,Stockholms kommun,Bostadsrättslägenhet,bostadsratt,False,False,False,False,False,6 795 000 kr,106 172 kr/m²,False,3 rum,5 850 kr/mån,<span>36</span> dagar,36,False,None,https://bilder.hemnet.se/images/itemgallery_S/...,https://bilder.hemnet.se/images/itemgallery_M/...,https://www.hemnet.se/bostad/lagenhet-3rum-gam...,"[{'category': 'product', 'identifier': 'premiu...",[],0,False,False,Spara,https://bilder.hemnet.se/images/broker_logo_2/...,HusmanHagberg Södermalm/Gamla Stan,"Gamla Stan, Stockholms kommun",False,False,"{'living_area': '64 m²', 'supplemental_area': ...",19325173,common_listing,premium,active,for_sale,NaN,gamla_stan,20221217,None,None,None
1,19102415,"[59.32596899944557, 18.074948653244743]",Skeppsbron 6 / Skeppar Karls Gränd 2A,Stockholms kommun,Bostadsrättslägenhet,bostadsratt,False,False,False,False,False,14 995 000 kr,99 305 kr/m²,False,4 rum,7 909 kr/mån,<span>40</span> dagar,40,False,None,https://bilder.hemnet.se/images/itemgallery_S/...,https://bilder.hemnet.se/images/itemgallery_M/...,https://www.hemnet.se/bostad/lagenhet-4rum-gam...,"[{'category': 'product', 'identifier': 'premiu...",[],0,False,False,Spara,https://bilder.hemnet.se/images/broker_logo_2/...,Ambassadör Fastighetsmäkleri AB,"Gamla Stan, Stockholms kommun",False,False,"{'living_area': '151 m²', 'supplemental_area':...",19102415,common_listing,premium,active,for_sale,NaN,gamla_stan,20221217,None,None,None
2,19158120,"[59.32439338293433, 18.068599264461106]",Stora Nygatan 22,Stockholms kommun,Bostadsrättslägenhet,bostadsratt,False,False,False,False,False,19 800 000 kr,113 143 kr/m²,True,6 rum,7 999 kr/mån,<span>78</span> dagar,78,False,None,https://bilder.hemnet.se/images/itemgallery_S/...,https://bilder.hemnet.se/images/itemgallery_M/...,https://www.hemnet.se/bostad/lagenhet-6rum-gam...,"[{'category': 'product', 'identifier': 'plus',...",[],0,False,False,Spara,https://bilder.hemnet.se/images/broker_logo_2/...,Eklund Stockholm New York,"Gamla stan, Stockholms kommun",False,False,"{'living_area': '175 m²', 'supplemental_area':...",19158120,common_listing,plus,active,for_sale,-10.0,gamla_stan,20221217,None,None,None

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 717 entries, 0 to 124
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id                               717 non-null    int64
 1   coordinate                       717 non-null    object
 2   address                          717 non-null    object
 3   location_name                    717 non-null    object
 4   typeSummary                      717 non-null    object
 5   iconName                         717 non-null    object
 6   project                          717 non-null    bool
 7   new_construction                 717 non-null    bool
 8   ongoing_bidding                  717 non-null    bool
 9   foreclosure                      717 non-null    bool
 10  upcoming                         717 non-null    bool
 11  price                            716 non-null    object
 12  price_per_area                   702 non-null    object
 13  has_price_change                 717 non-null    bool
 14  rooms                            714 non-null    object
 15  fee                              706 non-null    object
 16  age_string                       717 non-null    object
 17  age                              717 non-null    int64
 18  deactivated_before_open_house    717 non-null    bool
 19  land_area                        8 non-null      object
 20  small_image_url                  717 non-null    object
 21  medium_image_url                 717 non-null    object
 22  url                              717 non-null    object
 23  labels                           717 non-null    object
 24  state_labels                     717 non-null    object
 25  visible_project_units            717 non-null    int64
 26  show_visible_project_units       717 non-null    bool
 27  user_saved                       717 non-null    bool
 28  save_button_label                717 non-null    object
 29  broker_logo_url                  708 non-null    object
 30  broker_agency_name               717 non-null    object
 31  locations_string                 717 non-null    object
 32  should_display_showings          717 non-null    bool
 33  should_highlight_showings        717 non-null    bool
 34  living_space.table               717 non-null    object
 35  trackingData.listingId           717 non-null    object
 36  trackingData.listingType         717 non-null    object
 37  trackingData.listingPackageType  717 non-null    object
 38  trackingData.listingState        717 non-null    object
 39  trackingData.listingStatus       717 non-null    object
 40  price_change                     128 non-null    float64
 41  area                             717 non-null    object
 42  date                             717 non-null    object
 43  broker_name                      16 non-null     object
 44  broker_phone                     16 non-null     object
 45  broker_email                     16 non-null     object
dtypes: bool(11), float64(1), int64(3), object(31)
memory usage: 209.4+ KB

In [6]:
df_dropped=df.drop(
    [
        'project',
        'new_construction',
        'iconName',
        'land_area',
        'user_saved',
        'save_button_label',
        'broker_logo_url',
        'broker_name',
        'broker_phone',
        'broker_email',
        'age_string',
        'show_visible_project_units',
        'should_display_showings',
        'upcoming'
    ],
    axis=1)
df_dropped

           id                                coordinate                                address      location_name                        typeSummary  ongoing_bidding  foreclosure             price     price_per_area  has_price_change  rooms               fee  age  deactivated_before_open_house                                    small_image_url                                   medium_image_url                                                url                                             labels                                       state_labels  visible_project_units                                 broker_agency_name                          locations_string  should_highlight_showings                                 living_space.table trackingData.listingId trackingData.listingType trackingData.listingPackageType trackingData.listingState trackingData.listingStatus  price_change        area      date
0    19325173                  [59.3239555, 18.0685062]                       Lilla Nygatan 11  Stockholms kommun               Bostadsrättslägenhet            False        False      6 795 000 kr      106 172 kr/m²             False  3 rum      5 850 kr/mån   36                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-3rum-gam...  [{'category': 'product', 'identifier': 'premiu...                                                 []                      0                 HusmanHagberg Södermalm/Gamla Stan             Gamla Stan, Stockholms kommun                      False  {'living_area': '64 m²', 'supplemental_area': ...               19325173           common_listing                         premium                    active                   for_sale           NaN  gamla_stan  20221217
1    19102415   [59.32596899944557, 18.074948653244743]  Skeppsbron 6 / Skeppar Karls Gränd 2A  Stockholms kommun               Bostadsrättslägenhet            False        False     14 995 000 kr       99 305 kr/m²             False  4 rum      7 909 kr/mån   40                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-4rum-gam...  [{'category': 'product', 'identifier': 'premiu...                                                 []                      0                    Ambassadör Fastighetsmäkleri AB             Gamla Stan, Stockholms kommun                      False  {'living_area': '151 m²', 'supplemental_area':...               19102415           common_listing                         premium                    active                   for_sale           NaN  gamla_stan  20221217
2    19158120   [59.32439338293433, 18.068599264461106]                       Stora Nygatan 22  Stockholms kommun               Bostadsrättslägenhet            False        False     19 800 000 kr      113 143 kr/m²              True  6 rum      7 999 kr/mån   78                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-6rum-gam...  [{'category': 'product', 'identifier': 'plus',...                                                 []                      0                          Eklund Stockholm New York             Gamla stan, Stockholms kommun                      False  {'living_area': '175 m²', 'supplemental_area':...               19158120           common_listing                            plus                    active                   for_sale         -10.0  gamla_stan  20221217
3    18994274   [59.32494731233097, 18.073308919077213]                        Baggensgatan 12  Stockholms kommun  Lägenhet, andel i bostadsförening             True        False     11 895 000 kr      143 313 kr/m²             False  4 rum          1 kr/mån  119                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-4rum-gam...                                                 []  [{'category': 'state', 'identifier': 'ongoing_...                      0                    Wallenberg Fastighetsförmedling             Gamla Stan, Stockholms kommun                      False  {'living_area': '83 m²', 'supplemental_area': ...               18994274           common_listing                           basic                    active                   for_sale           NaN  gamla_stan  20221217
4    18953936   [59.32418950642289, 18.073433864314342]                        Baggensgatan 21  Stockholms kommun               Bostadsrättslägenhet             True        False     19 500 000 kr       96 059 kr/m²              True  4 rum      8 270 kr/mån  131                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-4rum-gam...  [{'category': 'product', 'identifier': 'plus',...  [{'category': 'state', 'identifier': 'ongoing_...                      0                          Eklund Stockholm New York             Gamla stan, Stockholms kommun                      False  {'living_area': '203 m²', 'supplemental_area':...               18953936           common_listing                            plus                    active                   for_sale          -7.0  gamla_stan  20221217
..        ...                                       ...                                    ...                ...                                ...              ...          ...               ...                ...               ...    ...               ...  ...                            ...                                                ...                                                ...                                                ...                                                ...                                                ...                    ...                                                ...                                       ...                        ...                                                ...                    ...                      ...                             ...                       ...                        ...           ...         ...       ...
120  18821279  [59.338731747003905, 18.035011132523685]                  Bråvallagatan 8, 5 tr  Stockholms kommun               Bostadsrättslägenhet            False        False      3 500 000 kr      134 615 kr/m²              True  1 rum      2 230 kr/mån  114                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-1rum-bir...  [{'category': 'feature', 'identifier': 'elevat...                                                 []                      0                    Ambassadör Fastighetsmäkleri AB              Birkastan, Stockholms kommun                      False  {'living_area': '26 m²', 'supplemental_area': ...               18821279           common_listing                           basic                    active                   for_sale          17.0    vasastan  20221217
121  18991743                    [59.34305, 18.0319862]                         Väringgatan 27  Stockholms kommun               Bostadsrättslägenhet            False        False      3 500 000 kr      109 375 kr/m²              True  1 rum      2 153 kr/mån  120                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-1rum-vas...  [{'category': 'product', 'identifier': 'premiu...                                                 []                      0  Länsförsäkringar Fastighetsförmedling Stockhol...   Vasastan - Birkastan, Stockholms kommun                      False  {'living_area': '32 m²', 'supplemental_area': ...               18991743           common_listing                         premium                    active                   for_sale          17.0    vasastan  20221217
122  18987175                    [59.348644, 18.034342]                 Hagaesplanaden 63, 7tr  Stockholms kommun               Bostadsrättslägenhet            False        False      3 595 000 kr      117 869 kr/m²             False  1 rum      2 005 kr/mån  121                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-1rum-vas...  [{'category': 'feature', 'identifier': 'balcon...                                                 []                      0               Fastighetsbyrån Stockholm - Vasastan  Vasastan - Hagastaden, Stockholms kommun                      False  {'living_area': '30,5 m²', 'supplemental_area'...               18987175           common_listing                           basic                    active                   for_sale           NaN    vasastan  20221217
123  18669396                  [59.3489761, 18.0394936]                          Dalagatan 102  Stockholms kommun               Bostadsrättslägenhet            False        False      4 095 000 kr      120 441 kr/m²             False  2 rum      2 364 kr/mån  169                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-2rum-sto...  [{'category': 'type', 'identifier': 'new_const...                                                 []                      0                                             BESQAB              Stockholm, Stockholms kommun                      False  {'living_area': '34 m²', 'supplemental_area': ...               18669396             project_unit                    not_selected                    active                   for_sale           NaN    vasastan  20221217
124  16998076                     [59.3489761, 18.0395]                      Legera Hagastaden  Stockholms kommun               Bostadsrättslägenhet            False        False  fr. 3 995 000 kr  fr. 117 500 kr/m²             False  2 rum  fr. 2 364 kr/mån  379                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/nybyggnadsprojekt/hagast...  [{'category': 'type', 'identifier': 'new_const...  [{'category': 'state', 'identifier': 'units_le...                      4                                             BESQAB  Hagastaden - Vasastan, Stockholms kommun                      False  {'living_area': '34 m²', 'supplemental_area': ...               16998076                  project                    not_selected                    active                   for_sale           NaN    vasastan  20221217

[717 rows x 32 columns]

In [7]:
df_dropped['state_labels'].value_counts()

[{'category': 'state', 'identifier': 'ongoing_bidding', 'priority': 5, 'text': 'Budgivning pågår'}]                        116
[{'category': 'state', 'identifier': 'ongoing_verified_bidding', 'priority': 4, 'text': 'Budgivning med BankID pågår'}]     26
[{'category': 'state', 'identifier': 'removed_before_showing', 'priority': 2, 'text': 'Borttagen före visning'}]            16
[{'category': 'state', 'identifier': 'highlighted_showing', 'priority': 8, 'text': 'Imorgon kl 13:00'}]                     10
[{'category': 'state', 'identifier': 'highlighted_showing', 'priority': 8, 'text': 'Imorgon kl 12:00'}]                      6
                                                                                                                          ...
[]                                                                                                                           1
[]                                                                                                                           1
[]                                                                                                                           1
[]                                                                                                                           1
[]                                                                                                                           1
Name: state_labels, Length: 529, dtype: int64

In [9]:
#get the labels column to work with
series_temp=df_dropped[['labels','id']]
series_temp.head(5)

                                              labels        id
0  [{'category': 'product', 'identifier': 'premiu...  19325173
1  [{'category': 'product', 'identifier': 'premiu...  19102415
2  [{'category': 'product', 'identifier': 'plus',...  19158120
3                                                 []  18994274
4  [{'category': 'product', 'identifier': 'plus',...  18953936

In [10]:
#make series to json then back to df again
js=series_temp.to_json(orient='records')
d1=pd.read_json(js)

d1

                                                labels        id
0    [{'category': 'product', 'identifier': 'premiu...  19325173
1    [{'category': 'product', 'identifier': 'premiu...  19102415
2    [{'category': 'product', 'identifier': 'plus',...  19158120
3                                                   []  18994274
4    [{'category': 'product', 'identifier': 'plus',...  18953936
..                                                 ...       ...
712  [{'category': 'feature', 'identifier': 'elevat...  18821279
713  [{'category': 'product', 'identifier': 'premiu...  18991743
714  [{'category': 'feature', 'identifier': 'balcon...  18987175
715  [{'category': 'type', 'identifier': 'new_const...  18669396
716  [{'category': 'type', 'identifier': 'new_const...  16998076

[717 rows x 2 columns]

In [11]:

d2=pd.json_normalize(d1['labels'])
d2

                                                     0                                                  1                                                  2                                                  3     4
0    {'category': 'product', 'identifier': 'premium...                                               None                                               None                                               None  None
1    {'category': 'product', 'identifier': 'premium...                                               None                                               None                                               None  None
2    {'category': 'product', 'identifier': 'plus', ...                                               None                                               None                                               None  None
3                                                 None                                               None                                               None                                               None  None
4    {'category': 'product', 'identifier': 'plus', ...  {'category': 'feature', 'identifier': 'balcony...                                               None                                               None  None
..                                                 ...                                                ...                                                ...                                                ...   ...
712  {'category': 'feature', 'identifier': 'elevato...                                               None                                               None                                               None  None
713  {'category': 'product', 'identifier': 'premium...  {'category': 'feature', 'identifier': 'elevato...                                               None                                               None  None
714  {'category': 'feature', 'identifier': 'balcony...  {'category': 'feature', 'identifier': 'elevato...                                               None                                               None  None
715  {'category': 'type', 'identifier': 'new_constr...  {'category': 'feature', 'identifier': 'occupan...  {'category': 'feature', 'identifier': 'balcony...  {'category': 'feature', 'identifier': 'elevato...  None
716  {'category': 'type', 'identifier': 'new_constr...                                               None                                               None                                               None  None

[717 rows x 5 columns]

In [12]:
d2.shape

(717, 5)

In [14]:
#list with frames containing each column in expanded df
lista=[]
for i in range(0,d2.shape[1]):
    lista.append(pd.json_normalize(d2[i]))
    #print(dict(lista[i])['identifier'].value_counts())

#lista[0]['identifier'].value_counts()
lista[2]

    category identifier  priority     text
0        NaN        NaN       NaN      NaN
1        NaN        NaN       NaN      NaN
2        NaN        NaN       NaN      NaN
3        NaN        NaN       NaN      NaN
4        NaN        NaN       NaN      NaN
..       ...        ...       ...      ...
712      NaN        NaN       NaN      NaN
713      NaN        NaN       NaN      NaN
714      NaN        NaN       NaN      NaN
715  feature    balcony      17.0  Balkong
716      NaN        NaN       NaN      NaN

[717 rows x 4 columns]

In [15]:
lista[2].value_counts()

category  identifier    priority  text
feature   elevator      19.0      Hiss          222
          balcony       17.0      Balkong        34
          patio         18.0      Uteplats       20
          tenure_owned  20.0      Äganderätt      1
dtype: int64

In [10]:
#loop thru the features for all columns and add it all to an array, then logical or all bools into one
import numpy

#how to get a list of all identifiers in a category feature?
feature_list=['balcony','elevator','patio','tenure_owned']
compact_df_list=[]

for f in feature_list:
    series=[]
    for d in lista:
        series.append(np.where((d['identifier']==f),True,False))
    narr=numpy.array(series)
    reducedarr=np.logical_or.reduce((narr))
    compact_df_list.append(pd.DataFrame(reducedarr,columns=[f]))

In [11]:
#expand the livingspace.table
series_livingspace=df_dropped['living_space.table']
df_livingspace=pd.json_normalize(series_livingspace)
#df_livingspace.reset_index()

d1.reset_index(drop=True)

df_livingspace.reset_index(drop=True)

In [12]:
features=pd.concat(compact_df_list,axis=1)
features

     balcony  elevator  patio  tenure_owned
0      False     False  False         False
1      False     False  False         False
2      False     False  False         False
3      False     False  False         False
4       True     False  False         False
..       ...       ...    ...           ...
712    False      True  False         False
713    False      True  False         False
714     True      True  False         False
715     True      True  False         False
716    False     False  False         False

[717 rows x 4 columns]

df_dropped.reset_index(drop=True).head(2)

In [13]:

merged_dfs=pd.concat([features,df_livingspace,d1],axis=1)
merged_dfs

     balcony  elevator  patio  tenure_owned living_area supplemental_area                                             labels        id
0      False     False  False         False       64 m²              None  [{'category': 'product', 'identifier': 'premiu...  19325173
1      False     False  False         False      151 m²              None  [{'category': 'product', 'identifier': 'premiu...  19102415
2      False     False  False         False      175 m²              None  [{'category': 'product', 'identifier': 'plus',...  19158120
3      False     False  False         False       83 m²              None                                                 []  18994274
4       True     False  False         False      203 m²              None  [{'category': 'product', 'identifier': 'plus',...  18953936
..       ...       ...    ...           ...         ...               ...                                                ...       ...
712    False      True  False         False       26 m²              None  [{'category': 'feature', 'identifier': 'elevat...  18821279
713    False      True  False         False       32 m²              None  [{'category': 'product', 'identifier': 'premiu...  18991743
714     True      True  False         False     30,5 m²              None  [{'category': 'feature', 'identifier': 'balcon...  18987175
715     True      True  False         False       34 m²              None  [{'category': 'type', 'identifier': 'new_const...  18669396
716    False     False  False         False       34 m²              None  [{'category': 'type', 'identifier': 'new_const...  16998076

[717 rows x 8 columns]

In [14]:
#merge it all
dfs = [df_dropped.set_index('id'),merged_dfs.set_index('id')]
all=pd.concat(dfs, axis=1)
all.drop(['labels','living_space.table'],axis=1,inplace=True)

In [15]:
all.head(2)

                                       coordinate                                address      location_name           typeSummary  ongoing_bidding  foreclosure          price price_per_area  has_price_change  rooms           fee  age  deactivated_before_open_house                                    small_image_url                                   medium_image_url                                                url state_labels  visible_project_units                  broker_agency_name               locations_string  should_highlight_showings trackingData.listingId trackingData.listingType trackingData.listingPackageType trackingData.listingState trackingData.listingStatus  price_change        area      date  balcony  elevator  patio  tenure_owned living_area supplemental_area
id
19325173                 [59.3239555, 18.0685062]                       Lilla Nygatan 11  Stockholms kommun  Bostadsrättslägenhet            False        False   6 795 000 kr  106 172 kr/m²             False  3 rum  5 850 kr/mån   36                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-3rum-gam...           []                      0  HusmanHagberg Södermalm/Gamla Stan  Gamla Stan, Stockholms kommun                      False               19325173           common_listing                         premium                    active                   for_sale           NaN  gamla_stan  20221217    False     False  False         False       64 m²              None
19102415  [59.32596899944557, 18.074948653244743]  Skeppsbron 6 / Skeppar Karls Gränd 2A  Stockholms kommun  Bostadsrättslägenhet            False        False  14 995 000 kr   99 305 kr/m²             False  4 rum  7 909 kr/mån   40                          False  https://bilder.hemnet.se/images/itemgallery_S/...  https://bilder.hemnet.se/images/itemgallery_M/...  https://www.hemnet.se/bostad/lagenhet-4rum-gam...           []                      0     Ambassadör Fastighetsmäkleri AB  Gamla Stan, Stockholms kommun                      False               19102415           common_listing                         premium                    active                   for_sale           NaN  gamla_stan  20221217    False     False  False         False      151 m²              None

In [16]:
new=all
#new.columns = new.columns.str.replace('trackingData.', '')

In [17]:

new.to_parquet('../data/transformed_data.parquet',engine='pyarrow')
new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 717 entries, 19325173 to 16998076
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   coordinate                       717 non-null    object
 1   address                          717 non-null    object
 2   location_name                    717 non-null    object
 3   typeSummary                      717 non-null    object
 4   ongoing_bidding                  717 non-null    bool
 5   foreclosure                      717 non-null    bool
 6   price                            716 non-null    object
 7   price_per_area                   702 non-null    object
 8   has_price_change                 717 non-null    bool
 9   rooms                            714 non-null    object
 10  fee                              706 non-null    object
 11  age                              717 non-null    int64
 12  deactivated_before_open_house    717 non-null    bool
 13  small_image_url                  717 non-null    object
 14  medium_image_url                 717 non-null    object
 15  url                              717 non-null    object
 16  state_labels                     717 non-null    object
 17  visible_project_units            717 non-null    int64
 18  broker_agency_name               717 non-null    object
 19  locations_string                 717 non-null    object
 20  should_highlight_showings        717 non-null    bool
 21  trackingData.listingId           717 non-null    object
 22  trackingData.listingType         717 non-null    object
 23  trackingData.listingPackageType  717 non-null    object
 24  trackingData.listingState        717 non-null    object
 25  trackingData.listingStatus       717 non-null    object
 26  price_change                     128 non-null    float64
 27  area                             717 non-null    object
 28  date                             717 non-null    object
 29  balcony                          717 non-null    bool
 30  elevator                         717 non-null    bool
 31  patio                            717 non-null    bool
 32  tenure_owned                     717 non-null    bool
 33  living_area                      714 non-null    object
 34  supplemental_area                35 non-null     object
dtypes: bool(9), float64(1), int64(2), object(23)
memory usage: 157.5+ KB

#how to get a list of all identifiers in a category feature?
feature_list=['balcony','elevator','patio','tenure_owned']
flistnow=0
balcony_series=[]
#loop thru all columns getting one identifier only
for d in lista:
    balcony_series.append(np.where((d['identifier']==feature_list[flistnow])|(d['identifier']==feature_list[flistnow])|(d['identifier']==feature_list[flistnow])|(d['identifier']==feature_list[flistnow]),True,False))
#d40['elevator']=np.where((d40['identifier']=='elevator')|(d41['identifier']=='elevator')|(d42['identifier']=='elevator')|(d43['identifier']=='elevator'),True,False)
#d40['patio']=np.where((d40['identifier']=='patio')|(d41['identifier']=='patio')|(d42['identifier']=='patio')|(d43['identifier']=='patio'),True,False)
balcony_series[0]

import numpy
compact_df_list=[]
narr_balcony=numpy.array(balcony_series)
reducedarr=np.logical_or.reduce((narr_balcony))
#pd.DataFrame(reducedarr).rename(columns={flistnow:feature_list[flistnow]})
compact_df_list.append(pd.DataFrame(reducedarr,columns=[feature_list[flistnow]]))
compact_df_list

# boolisar=pd.DataFrame(series).T
# boolisar['balcony']=boolisar.any(axis='columns')
# boolisar.drop([0,1,2,3],axis=1,inplace=True)
boolisar.value_counts()

js2=d2.to_json(orient='records')
d3=pd.read_json(js2)
d3

d40=pd.json_normalize(d3[0])
d40.value_counts()

d41=pd.json_normalize(d3[1])
d41.value_counts()

d42=pd.json_normalize(d3[2])
d42.value_counts()

d43=pd.json_normalize(d3[3])
d43.value_counts()
dict(d40)['identifier'].value_counts()



d40['balcony']=np.where((d40['identifier']=='balcony')|(d41['identifier']=='balcony')|(d42['identifier']=='balcony')|(d43['identifier']=='balcony'),True,False)
d40['elevator']=np.where((d40['identifier']=='elevator')|(d41['identifier']=='elevator')|(d42['identifier']=='elevator')|(d43['identifier']=='elevator'),True,False)
d40['patio']=np.where((d40['identifier']=='patio')|(d41['identifier']=='patio')|(d42['identifier']=='patio')|(d43['identifier']=='patio'),True,False)
d40

df_temp=pd.json_normalize(series_temp)
df_temp